FROM centos
ENV REDIS_DAEMONIZE="no" \
    REDIS_PIDFILE=/var/run/redis.pid \
    REDIS_PORT=6379 \
    REDIS_TCP_BACKLOG=511 \
    REDIS_BIND=127.0.0.1 \
    REDIS_TCP_KEEPALIVE=0 \
    REDIS_LOGLEVEL=notice \
    REDIS_LOGFILE=/var/log/redis/redis.log \
    REDIS_DATABASES=16 \
    REDIS_SAVE="900 1" \
    REDIS_STOP_WRITES_ON_BGSAVE_ERROR=yes \
    REDIS_RDBCOMPRESSION=yes \
    REDIS_RDBCHECKSUM=yes \
    REDIS_DBFILENAME=dump.rdb \
    REDIS_DIR=/var/lib/redis \
    REDIS_SLAVE_SERVE_STALE_DATA=yes \
    REDIS_SLAVE_READ_ONLY=yes \
    REDIS_REPL_DISKLESS_SYNC=no \
    REDIS_REPL_DISKLESS_SYNC_DELAY=5 \
    REDIS_REPL_DISABLE_TCP_NODELAY=no \
    REDIS_SLAVE_PRIORITY=100 \
    REDIS_APPENDONLY=no \
    REDIS_APPENDFILENAME=appendonly.aof \
    REDIS_APPENDFSYNC=everysec \
    REDIS_NO_APPENDFSYNC_ON_REWRITE=no \
    REDIS_AUTO_AOF_REWRITE_PERCENTAGE=100 \
    REDIS_AUTO_AOF_REWRITE_MIN_SIZE=64mb \
    REDIS_AOF_LOAD_TRUNCATED=yes \
    REDIS_LUA_TIME_LIMIT=5000 \
    REDIS_SLOWLOG_LOG_SLOWER_THAN=10000 \
    REDIS_SLOWLOG_MAX_LEN=128 \
    REDIS_LATENCY_MONITOR_THRESHOLD=0 \
    REDIS_NOTIFY_KEYSPACE_EVENTS='""' \
    REDIS_HASH_MAX_ZIPLIST_ENTRIES=512 \
    REDIS_HASH_MAX_ZIPLIST_VALUE=64 \
    REDIS_LIST_MAX_ZIPLIST_ENTRIES=512 \
    REDIS_LIST_MAX_ZIPLIST_VALUE=64 \
    REDIS_SET_MAX_INTSET_ENTRIES=512 \
    REDIS_ZSET_MAX_ZIPLIST_ENTRIES=128 \
    REDIS_ZSET_MAX_ZIPLIST_VALUE=64 \
    REDIS_HLL_SPARSE_MAX_BYTES=3000 \
    REDIS_ACTIVEREHASHING=yes \
    REDIS_CLIENT_OUTPUT_BUFFER_LIMIT="normal 0 0 0" \
    REDIS_CLIENT_OUTPUT_BUFFER_LIMIT="slave 256mb 64mb 60" \
    REDIS_CLIENT_OUTPUT_BUFFER_LIMIT="pubsub 32mb 8mb 60" \
    REDIS_HZ=10

RUN yum install -y wget epel-release && \
  yum install -y logrotate jemalloc && \
  wget -O /tmp/redis.rpm ftp://195.220.108.108/linux/remi/enterprise/7/test/x86_64/redis-3.0.0-2.el7.remi.x86_64.rpm && \
  rpm -i /tmp/redis.rpm && \
  yum clean all
